### ISSUE TITLE
Problem with the display OUTput

### ISSUE THREAD

**Issue by wawachief** [dangrie158/SAP-1#3]
I have a last issue with the computer : the 7-segments display don't work properly. I don't understand how this is supposed to work with the resistors array.
To fix that, I desoldered the resistors and soldered the output decoder D0->D7 directly to the 7-segments display, assuming the IC would limit the current as ben suggested in his videos.

**Comment by dangrie158** [comment]
Mhh, I had no issues. Do you use blue or white displays? 
I just added a section in the docs explaining possible solutions (lowering the network values, jumping it out completely), although the "right" solution would be to add a drive transistor for each network, but even when using a IC (like a ULNXXX series) the rerouting of the board and additional space needed probably makes it not worth just for the "correct" solution instead of a fix.
